# -*- coding: utf-8 -*-
"""clustering_chemo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UvGDjat-v7CzW95ritS-7qukTMdbZj8Q
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('Mall_Customers.csv')

df.head()

df.drop(columns=['CustomerID'], inplace=True)

df.head()

df['Genre'] = df['Genre'].apply(lambda x: 0 if x=='Male' else 1)
df.head()

#elbow method
wCSS = []
for i in range(1,11):
    kmeans = KMeans(n_clusters = i, init = 'k-means++', max_iter = 300, n_init = 10)
    kmeans.fit(df)
    wCSS.append(kmeans.inertia_) #Collects all of the within cluster sum of squares
plt.plot(range(1,11), wCSS)
plt.title('Elbow Method')
plt.xlabel('Clusters')
plt.ylabel('wCSS')
plt.show()

kmeans = KMeans(n_clusters=6 , random_state=0, n_init="auto").fit(df)

kmeans.predict([[0, 20, 15, 30]])[0]

kmeans.cluster_centers_

#PCA

pca = PCA(n_components=3)
df_3d = pca.fit_transform(df)

# Get the explained variance ratio for each principal component
explained_variance_ratio = pca.explained_variance_ratio_

# Print the percentage of variance explained by each PC
for i, variance_ratio in enumerate(explained_variance_ratio):
    print(f"PC{i+1}: {variance_ratio:.2%}")

cluster_labels = kmeans.predict(df)

v = df_3d
v = np.append(v, cluster_labels.reshape(-1,1), 1)
df = pd.DataFrame(v, columns=['PC1', 'PC2','PC3',"Cluster"])
print (df)

fig = plt.figure(figsize=(10,10))
ax = fig.add_subplot(111, projection='3d')
x = np.array(df['PC1'])
y = np.array(df['PC2'])
z = np.array(df['PC3'])

ax.scatter(x,y,z, marker="s", c=df["Cluster"], s=40, cmap="RdBu")

plt.show()