# -*- coding: utf-8 -*-
"""f1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YFHcUGXnnTig041eRnrXTl-Hnnnhqb4Z

1)
pandas assignment.

create a series from  100, 50, 25, 10, 5.

call two first rows of this series.

call last two rows of this series.

changw the index to a, b, c, d, f.

2)
define a function that would do : x^2+5x+5 , use def function.


then put 5 and 3 in the mentioned function and print the answer.

3)object oriented assignmet(emtiazi)

create a class that consist of model and price , then write function in classs which is creating new price(ex. price = price+100) and write another function that would add new model (you can use append)
"""